export const products = [
  {
    id: 8,
    name: "Proteína de Chocolate",
    price: 96990,
    instock: 100,
    description: "Proteina aislada de suero de leche sabor Chocolate 5 libras.",
    imgSrc: "/img/iso100.png",
    categoryId: 1,
  },
  {
    id: 1,
    name: "Arroz",
    price: 1570,
    instock: 100,
    description: "Arroz tucapel 1kg.",
    imgSrc: "/img/arroz.png",
    categoryId: 3,
  },
  {
    id: 2,
    name: "Avena Instantanea",
    price: 1990,
    instock: 100,
    description: "Avena instantanea 750g Quaker.",
    imgSrc: "/img/avena.png",
    categoryId: 3,
  },
  {
    id: 3,
    name: "Carne molida 4%",
    price: 4390,
    instock: 5,
    description: "Carne molida 4% de grasa, 320gr.",
    imgSrc: "/img/carneMolida.png",
    categoryId: 1,
  },
  {
    id: 4,
    name: "Bandeja de huevos",
    price: 5990,
    instock: 100,
    description: "Bandeja de 30 huevos tamaño jumbo.",
    imgSrc: "/img/huevos.png",
    categoryId: 1,
  },
  {
    id: 5,
    name: "Pechuga Deshuesada",
    price: 3999,
    instock: 40,
    description: "Pechuga de pollo deshuesada 700gr.",
    imgSrc: "/img/pechugapollo.png",
    categoryId: 1,
  },
  {
    id: 6,
    name: "Ketchup",
    price: 3500,
    instock: 40,
    description: "Ketchup sin azucar añadida 700gr.",
    imgSrc: "./img/c7.png",
    categoryId: 4,
  },
  {
    id: 7,
    name: "Leche descremada",
    price: 1150,
    instock: 40,
    description: "Leche descremada sin lactosa 1 Litro.",
    imgSrc: "/img/lechedescremada.png",
    categoryId: 2,
  },
];
